import { CliOption } from "@/services/CliOptions.js";
import type { GitCommit } from "@/services/GitClient.js";
import { LocalConfig } from "@/services/LocalConfig.js";
import { WithModel } from "@/services/WithModel.js";
import * as LanguageModel from "@effect/ai/LanguageModel";
import { Effect } from "effect";
import {
  makeChangelogPrompt,
  makeCommitMessagePrompt,
  makePrDetailsPrompt,
  makePrLineReviewPrompt,
  makeReviewPrompt,
  makeTitlePrompt,
} from "./prompts.js";
import {
  ChangelogResponse,
  CommitMessage,
  PrDetails,
  PrReviewDetails,
  PrTitle,
} from "./schemas.js";

const orDie =
  (message: string) =>
  <A, E extends { message: string }, R>(self: Effect.Effect<A, E, R>) =>
    self.pipe(Effect.orDieWith((error) => `${message}: ${error.message}`));

export const makeReviewCommentTag = (username: string) =>
  `<!-- [gitai-review:${username}](https://github.com/lucas-barake/gitai) -->`;

const AUTOGENERATED_PATTERNS = [
  /pnpm-lock\.yaml/,
  /yarn\.lock/,
  /package-lock\.json/,
  /bun\.lockb?/,
  /\.lock$/,
  /lockfile/i,
  /coverage\/.*\.json/,
  /\.nyc_output\//,
  /node_modules\//,
  /\.next\//,
  /\.nuxt\//,
  /dist\//,
  /build\//,
  /\.git\//,
  /\.DS_Store/,
];

export const filterDiff = (rawDiff: string): string =>
  rawDiff
    .split("diff --git")
    .filter((part) => {
      if (!part.trim()) {
        return false;
      }
      const firstLine = part.substring(0, part.indexOf("\n"));
      return !AUTOGENERATED_PATTERNS.some((pattern) => pattern.test(firstLine));
    })
    .map((part) => `diff --git${part}`)
    .join("");

export const formatPrDescription = (details: PrDetails): string => {
  const fileSummaries = details.fileSummaries
    .map((summary) => `| ${summary.file} | ${summary.description} |`)
    .join("\n");

  return `${details.description}

<details>
<summary>Show a summary per file</summary>

| File | Description |
| ---- | ----------- |
${fileSummaries}
</details>`;
};

export const formatReviewAsMarkdown = (review: PrReviewDetails, username: string): string => {
  const reviewTag = makeReviewCommentTag(username);
  const reviewItems = review.review
    .map(
      (item) =>
        `**${item.file}:${item.line}**\n* [${item.category}] ${item.comment}\n\`\`\`\n${item.codeSnippet}\n\`\`\``,
    )
    .join("\n\n");

  return `${reviewTag}\n<details>\n<summary>Review</summary>\n\n${reviewItems}\n</details>`;
};

export class AiGenerator extends Effect.Service<AiGenerator>()("@gitai/AiGenerator", {
  dependencies: [WithModel.Default, LocalConfig.Default],
  effect: Effect.gen(function* () {
    const { withModel } = yield* WithModel;
    const localConfig = yield* LocalConfig;

    const generatePrDetails = Effect.fn("AiGenerator.generatePrDetails")(function* (diff: string) {
      const model = yield* CliOption("model");
      const context = yield* CliOption("context");
      const filteredDiff = filterDiff(diff);

      return yield* LanguageModel.generateObject({
        prompt: makePrDetailsPrompt(filteredDiff, context),
        schema: PrDetails,
      }).pipe(
        withModel(model),
        Effect.map((response) => ({
          title: response.value.title,
          body: formatPrDescription(response.value),
        })),
        orDie("Failed to generate PR details"),
      );
    });

    const generateCommitMessage = Effect.fn("AiGenerator.generateCommitMessage")(function* (
      diff: string,
    ) {
      const model = yield* CliOption("model");
      const context = yield* CliOption("context");
      const filteredDiff = filterDiff(diff);

      return yield* LanguageModel.generateObject({
        prompt: makeCommitMessagePrompt(filteredDiff, context),
        schema: CommitMessage,
      }).pipe(
        withModel(model),
        Effect.map((response) => response.value.message),
        orDie("Failed to generate commit message"),
      );
    });

    const generateTitle = Effect.fn("AiGenerator.generateTitle")(function* (diff: string) {
      const model = yield* CliOption("model");
      const context = yield* CliOption("context");
      const filteredDiff = filterDiff(diff);

      return yield* LanguageModel.generateObject({
        prompt: makeTitlePrompt(filteredDiff, context),
        schema: PrTitle,
      }).pipe(
        withModel(model),
        Effect.map((response) => response.value.title),
        orDie("Failed to generate PR title"),
      );
    });

    const generateReviewComment = Effect.fn("AiGenerator.generateReviewComment")(function* (
      diff: string,
    ) {
      const model = yield* CliOption("model");
      const context = yield* CliOption("context");
      const filteredDiff = filterDiff(diff);

      return yield* LanguageModel.generateObject({
        prompt: makeReviewPrompt(filteredDiff, context),
        schema: PrReviewDetails,
      }).pipe(
        withModel(model),
        Effect.map((response) => formatReviewAsMarkdown(response.value, localConfig.username)),
        orDie("Failed to generate review comment"),
      );
    });

    const generateChangelog = Effect.fn("AiGenerator.generateChangelog")(function* (
      commits: ReadonlyArray<GitCommit>,
    ) {
      const model = yield* CliOption("model");
      const context = yield* CliOption("context");

      return yield* LanguageModel.generateObject({
        prompt: makeChangelogPrompt(commits, context),
        schema: ChangelogResponse,
      }).pipe(
        withModel(model),
        Effect.map((response) => response.value),
        orDie("Failed to generate changelog"),
      );
    });

    const generatePrLineReview = Effect.fn("AiGenerator.generatePrLineReview")(function* (
      diff: string,
    ) {
      const model = yield* CliOption("model");
      const context = yield* CliOption("context");
      const filteredDiff = filterDiff(diff);

      return yield* LanguageModel.generateObject({
        prompt: makePrLineReviewPrompt(filteredDiff, context),
        schema: PrReviewDetails,
      }).pipe(
        withModel(model),
        Effect.map((response) => response.value),
        orDie("Failed to generate PR line review"),
      );
    });

    return {
      generatePrDetails,
      generateCommitMessage,
      generateTitle,
      generateReviewComment,
      generateChangelog,
      generatePrLineReview,
    } as const;
  }),
}) {}
